Corrijiendo errores de escritura
DavidMena-Q/Hyperblog pull request #1
Opened 2021-08-13 21:12 UTC by DavidMena-Q

No debimos pasar este error a main

2021-08-13 21:17 UTC, AnitaLaHuerfanit requested changes
En vez de hacer cambios directos mejor usa entidades HTML

2021-08-13 21:23 UTC, DavidMena-Q commented
Anita ya esta correjido Hazme el merge

2021-08-13 21:25 UTC, AnitaLaHuerfanit approved these changes
Perfecto haré el merge

2021-08-13 21:27 UTC, merged

2021-08-15 18:18 UTC, DavidMena-Q reviewed
perfect